title: Sahil Sachdeva #
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior IT Consultant
  <br><br>
  <a href="mailto:info.sahilsachdeva01@gmail.com">info.sahilsachdeva01@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/iamsachdeva//">LinkedIn Profile</a>
  </a> 
theme: jekyll-theme-minimal
